#!/bin/sh

case "$1" in
    start)
        echo "Starting misc-modules"
        cd /lib/modules/$(uname -r)/extra/
        /usr/sbin/module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping misc-modules"
        cd /lib/modules/$(uname -r)/extra/
        /usr/sbin/module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0